tuleap:
    image: enalean/tuleap-aio-dev
    volumes:
        - /srv/docker/nala:/data
        - /home/yannis/dev/tuleap:/usr/share/tuleap
    env_file:
        - tuleap-env
        - tuleap-env-ssh-key
    ports:
        - "80:80"
        - "443:443"
    links:
        - skydock

skydock:
    image: crosbymichael/skydock
    volumes:
        - /var/run/docker.sock:/docker.sock
    command: -ttl 30 -environment dev -s /docker.sock -domain nala -name tuleapcompose_skydns_1
    links:
        - skydns

skydns:
    image: crosbymichael/skydns
    ports:
        - "172.17.42.1:53:53/udp"
    command: -nameserver 8.8.8.8:53 -domain nala
